name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Basic Build
      run: cargo build --no-default-features
    - name: Default Build
      run: cargo build
    - name: Run all tests
      run: cargo test --all-features
